stages:
    - publish

publish:
    stage: publish
    script:
        - npm install
        - npm run build
        - npm publish --registry https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/npm/
    only:
        - dev
