name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{github.actor != 'chirpwireless-golang-builder[bot]'}}
    uses: chirpwireless/reusable-github-actions/.github/workflows/build-frontend-library.yml@main
    with:
        publish: ${{github.event_name != 'pull_request' && github.ref == 'refs/heads/main'}}
    permissions:
      contents: write
      packages: write
      checks: write
    secrets: inherit
