name: Publish

on:
    workflow_dispatch:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
    cancel-in-progress: true

jobs:
    build:
        if: ${{github.actor != 'chirpwireless-builder[bot]'}}
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            checks: write
        steps:
            - uses: actions/create-github-app-token@v1
              id: app-token
              with:
                  app-id: ${{ secrets.GOLANG_BUILDER_APP_ID }}
                  private-key: ${{ secrets.GOLANG_BUILDER_PRIVATE_KEY }}
                  owner: ${{ github.repository_owner }}
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ steps.app-token.outputs.token }}
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              # with:
              # node-version-file: '.nvmrc'
              # cache: 'yarn'
            - name: Install yarn dependencies
              run: yarn install
              # run: yarn install --frozen-lockfile
            - name: Run build
              run: yarn build
            - name: Publish package
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config user.name github-actions
                  git config user.email github-actions[bot]@users.noreply.github.com
                  echo "//npm.pkg.github.com/:_authToken=${{ env.NODE_AUTH_TOKEN }}" > ~/.npmrc
                  yarn version --minor
                  yarn publish
                  git push origin --follow-tags
